### ISSUE TITLE
Client connection issues in `nightly` build

### ISSUE THREAD

**Issue by BerserkeR-Git** [wg-easy/wg-easy#692]
While the new image starts up for me and the UI works, the connection itself doesn't, and I keep getting this:
```
2023-12-21T20:35:53.148Z Server Listening on http://0.0.0.0:51821/

2023-12-21T20:35:53.150Z WireGuard Loading configuration...

2023-12-21T20:35:53.153Z WireGuard Configuration loaded.

2023-12-21T20:35:53.153Z WireGuard Config saving...

2023-12-21T20:35:53.155Z WireGuard Config saved.

$ wg-quick down wg0

$ wg-quick up wg0

2023-12-21T20:35:53.288Z WireGuard Config syncing...

$ wg syncconf wg0 <(wg-quick strip wg0)

2023-12-21T20:35:53.318Z WireGuard Config synced.

2023-12-21T20:35:59.528Z Server New Session: i5sRsCUFkeLvjyauYOHTzzanEtQN3LVO

2023-12-21T20:37:07.814Z WireGuard Config saving...

2023-12-21T20:37:07.815Z WireGuard Config saved.

2023-12-21T20:37:07.815Z WireGuard Config syncing...

$ wg syncconf wg0 <(wg-quick strip wg0)

2023-12-21T20:37:07.848Z WireGuard Config synced.

2023-12-21T20:37:09.166Z WireGuard Config saving...

2023-12-21T20:37:09.168Z WireGuard Config saved.

2023-12-21T20:37:09.168Z WireGuard Config syncing...

$ wg syncconf wg0 <(wg-quick strip wg0)

2023-12-21T20:37:09.204Z WireGuard Config synced.
```
But the outside connection still works with the old image, weejewel/wg-easy (v7)
So the new image boots up but the outside connections aren't working and I'm not seeing any network traffic in the UI.

_Originally posted by @BerserkeR-Git in https://github.com/wg-easy/wg-easy/issues/682#issuecomment-1866922975_

**Comment by peterlewis** [comment]
Thank you for raising this, @BerserkeR-Git.

@pheiduck Do you think this may be related to the issue raised by @redstripes89 [downstream](https://github.com/peterlewis/wg-easy/issues/71)?

**Comment by pheiduck** [comment]
I am not sure where it came from maybe because I set the MTU fixed to 1420

**Comment by pheiduck** [comment]
@BerserkeR-Git please test: ghcr.io/wg-easy/wg-easy:development

**Comment by peterlewis** [comment]
Please note that the MTU will have been hardcoded into the downloaded `.conf`. Can you please download a fresh copy and re-import to WireGuard?

**Comment by peterlewis** [comment]
@pheiduck I'd suggest we merge the MTU reversion regardless as it is subsequently hardcoding the MTU into the .conf.

**Comment by pheiduck** [comment]
@BerserkeR-Git 
cd into the directory where your wg-easy lies. 
1. do: `docker compose down`
2. `docker system prune -a —volume`
3. `docker compose up -d`

**Comment by peterlewis** [comment]
Okay. So it's not MTU causing your issue, then. Thought glad it was brought up as ~always~ often good to remove rigid values where possible!

I'm wondering whether, and indeed suspect that this is a dependency regression, as opposed to being a result of rebase from downstream.

I would suggest we look to create a dev build based on @WeeJeWel's v8 release, but including the synology fix, and see how that works for you.

**Comment by peterlewis** [comment]
Sure thing. I've pushed that build to `development` so if you can re-pull and revert with your findings, then that'd be fab.

**Comment by rusty1281** [comment]
I just got home and tested this myself. The initial development image was (is) also working fine. I have just tested again (without the new pull).

In my previous testings I have removed MTU 1420 value on the client side automatically, as that was always "automatic" for me, so I didn't pay attention to it.

So just to confirm, even though the new correct helped Berserker, clearing the MTU value on the client side works like a charm. Maybe I should have mentioned it in the previous issue.

Great work again guys! Tnx!

**Comment by peterlewis** [comment]
Okay. Thank you, both.

@BerserkeR-Git I don't suspect your issue to be caused by dark mode, thankfully! 👍🏻 I think we may be looking at some kind of regression in one of the (multiple) node modules that have been patched. I'll continue to investigate.

@rusty1281 Thank you for letting me know all is good. I'm going to push the MTU reversion to nightly. If you can please, subsequently, head on over to `nightly` then that'd be lush.

**Comment by rusty1281** [comment]
> @rusty1281 Thank you for letting me know all is good. I'm going to push the MTU reversion to nightly. If you can please, subsequently, head on over to `nightly` then that'd be lush.

Ofc, I will test `nightly`as soon as you update the image.

**Comment by peterlewis** [comment]
@rusty1281 updated :)

**Comment by rusty1281** [comment]
> @rusty1281 updated :)

Nightly running with 0 issue. MTU on automatic for me.

<img width="815" alt="Screenshot 2023-12-21 at 23 47 50" src="https://github.com/wg-easy/wg-easy/assets/5110408/df9c6739-95e6-4566-aa15-6a1c5be69efe">

**Comment by peterlewis** [comment]
@rusty1281 excellent news! We'll leave the MTU reversion in-place then! Sorry for the inconvenience. I have created a separate issue for you at https://github.com/wg-easy/wg-easy/issues/694 so if you see regression of this, please update that separate issue.

We'll keep this issue, going forwards, to track (and look to resolve) @rusty1281's reported issue, which I think may be related to a regression in one of the node dependencies. We shall see!

**Comment by peterlewis** [comment]
Okay thank you @rusty1281. So both you and @BerserkeR-Git are running on Synology(?) and both experiencing the issue.

I suspect, as mentioned previously, we are looking at a note dependency regression. Will need to do some further troubleshooting alongside @pheiduck.

I will keep in touch! For now, the `development` image is `latest + synology fix` and anticipate the next update it sees will be related to your issue, so stick with that for now.

**Comment by rusty1281** [comment]
> > > @rusty1281
> > 
> > 
> > Nightly running with 0 issue. MTU on automatic for me.
> 
> I'm on nightly now but I'm getting the same result. I even tried it with a separate compose file and clean install, but I'm not getting a connection. I left MTU on auto as well, just like before with the dev build that was in fact working.

I have just tested this on my MacBook using the same setup as on my iPhone. I have connected to the internet over my iPhone and then activated WG. All works fine for me. Either on the phone or on the MacBook.

<img width="818" alt="Screenshot 2023-12-22 at 00 08 41" src="https://github.com/wg-easy/wg-easy/assets/5110408/db321e9d-8454-4838-acd7-a05a22a85171">

@peterlewis I have no issues at all. All working for me fine. I have tested with number of scenarios and with multiple Synology NAS boxes, no issues at all.

**Comment by peterlewis** [comment]
Oh crumbs! Sorry, @rusty1281, I had misread your quoted reply as being from you! I'm glad (positively delighted) you're not experiencing issues with the latest `nightly` release!

We will continue to look into @BerserkeR-Git's issue, given when the issue arose (rebase from downstream). As mentioned, I suspect node dependency.

**Comment by rusty1281** [comment]
No worries @peterlewis, let me know if I can validate any more updates and changes in the upcoming images. I have updates my [article(s)](https://www.blackvoid.club/wireguard-vpn-for-your-synology-nas/) that reference this WG solution (that is where most Syno reports came from), and will keep it up to date as this develops further.

**Comment by peterlewis** [comment]
Thank you, both, much appreciated.

**Comment by peterlewis** [comment]
@BerserkeR-Git, for your information, have pushed Synology fix (v9) to `latest` meaning that you can head on back to stable whilst we work through this issue.

If you're happy to help us test further, though, then that'd be lush. I'll drop a comment here when we've got progression on the issue.

**Comment by peterlewis** [comment]
The issues you are seeing may be related to those raised by @redstripes89 in my (now-archived) fork. I'm hoping he's able to test the `nightly` build here and report back with his experience.

**Comment by peterlewis** [comment]
@BerserkeR-Git can you please post your `docker-compose`, redacting any sensitive information?

Thanks!

**Comment by pheiduck** [comment]
The Port config looks not correct 
```
ports:
      - "redacted:51820/udp"
      - "51820:51821/tcp"
```

should be:

```
ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
```

**Comment by pheiduck** [comment]
@rusty1281 could you please post your docker compose for comparison?

**Comment by peterlewis** [comment]
Yes and if @redstripes89 and @hansnull are also happy to do so then that'd be great!

**Comment by LoV432** [comment]
Same issue here on Manjaro. The UI is working but no connection. Reverting to old version fixes the issue

```
wg-easy  | 2023-12-22T11:03:09.210Z Server Listening on http://0.0.0.0:51821
wg-easy  | 2023-12-22T11:03:09.212Z WireGuard Loading configuration...
wg-easy  | 2023-12-22T11:03:09.215Z WireGuard Configuration loaded.
wg-easy  | 2023-12-22T11:03:09.216Z WireGuard Config saving...
wg-easy  | 2023-12-22T11:03:09.221Z WireGuard Config saved.
wg-easy  | $ wg-quick down wg0
wg-easy  | $ wg-quick up wg0
wg-easy  | 2023-12-22T11:03:09.323Z WireGuard Config syncing...
wg-easy  | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy  | 2023-12-22T11:03:09.350Z WireGuard Config synced.
wg-easy  | 2023-12-22T11:03:33.938Z Server New Session: JOmgWtIsUSM6N7cJnVCiwPa2vJKxdXQp
```

```yaml
version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=REMOVED

      # Optional:
      - PASSWORD=REMOVED
      - WG_PORT=445
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=100.100.100.100
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt

    image: ghcr.io/wg-easy/wg-easy:nightly
#    image: lov432/wg-easy:7-weekly
    container_name: wg-easy
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "445:51820/udp"
      # - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      traefik_proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard.rule=Host(`REMOVED`)"
      - "traefik.http.routers.wireguard.entrypoints=websecure"
      - "traefik.http.routers.wireguard.tls.certresolver=production"
      - "traefik.http.routers.wireguard.tls.domains[0].main=REMOVED"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
      - "traefik.docker.network=traefik_proxy"


networks:
    traefik_proxy:
       external: true
```

**Comment by peterlewis** [comment]
@LoV432 please can you confirm that the latest stable fixes things for you?

**Comment by LoV432** [comment]
> @LoV432 please can you confirm that the latest stable fixes things for you?



Yes `image: ghcr.io/wg-easy/wg-easy` works just fine

![image](https://github.com/wg-easy/wg-easy/assets/60856741/926e3f3f-613f-4c79-926a-bba1ab5d9752)
```
wg-easy  | 2023-12-22T11:29:01.565Z Server Listening on http://0.0.0.0:51821
wg-easy  | 2023-12-22T11:29:01.566Z WireGuard Loading configuration...
wg-easy  | 2023-12-22T11:29:01.570Z WireGuard Configuration loaded.
wg-easy  | 2023-12-22T11:29:01.570Z WireGuard Config saving...
wg-easy  | 2023-12-22T11:29:01.571Z WireGuard Config saved.
wg-easy  | $ wg-quick down wg0
wg-easy  | $ wg-quick up wg0
wg-easy  | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy  | 2023-12-22T11:29:01.665Z WireGuard Config syncing...
wg-easy  | 2023-12-22T11:29:01.697Z WireGuard Config synced.
wg-easy  | 2023-12-22T11:29:09.565Z Server New Session: wOTr3J60OmsUTPpgo5I2gE7-SAp4q32m
```

**Comment by peterlewis** [comment]
Excellent. Thank you confirming.

**Comment by rusty1281** [comment]
I have just run the `latest` on my test and prod setup. Run with zero issue. LAN and WAN accessible as with v7.

**Comment by rusty1281** [comment]
> @rusty1281 could you please post your docker compose for comparison?

@pheiduck off here it is:

```
version: "3.5"
services:
  wgeasy:
    image: ghcr.io/wg-easy/wg-easy:latest
    network_mode: "bridge"
    container_name: wgeasy
    ports:
      - "51820:51820/udp"
      - "51821:51821"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - /volume1/docker/wgeasy:/etc/wireguard
    environment:
      - WG_HOST=<public IP or DDNS address>
      - PASSWORD=<Wireguard web ui password>
    restart: always
```

**Comment by redstripes89** [comment]
I just siwtched to v9 of this image and can confirm working also.

```yaml
version: "3.9"
services:
  wireguard:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: wireguard
    env_file: ./config/wireguard.env
    image: ghcr.io/wg-easy/wg-easy:9
    labels:
      traefik.docker.network: proxy
      traefik.enable: true
      traefik.http.routers.wireguard.entrypoints: websecure
      traefik.http.routers.wireguard.middlewares: default@file
      traefik.http.routers.wireguard.rule: Host(<removed>)
      traefik.http.routers.wireguard.service: wireguard
      traefik.http.routers.wireguard.tls: true
      traefik.http.routers.wireguard.tls.certresolver: tls_resolver
      traefik.http.services.wireguard.loadbalancer.server.port: 51821
    networks:
      proxy:
        ipv4_address: <removed>
    ports:
      - "<removed>:51820/udp"
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./wireguard:/etc/wireguard:rw
```

wireguard.env
```yaml
PASSWORD=<removed>
WG_PORT=<removed>
WG_HOST=<removed>
WG_DEFAULT_DNS=<removed>
```

**Comment by peterlewis** [comment]
@redstripes89 Thank you. Please can you try `nightly` and report back as to whether you have issues with that build?

**Comment by redstripes89** [comment]
> @redstripes89 Thank you. Please can you try `nightly` and report back as to whether you have issues with that build?

Nightly not working :(

**Comment by peterlewis** [comment]
Interesting. Thank you. What's your setup, @redstripes89? (VM, NAS etc.) Sorry if you've already said.

**Comment by redstripes89** [comment]
I'm using a Raspberry Pi 4B with latest DietPi OS v8.25, no NAS no VMs. 
Connecting from extern through DynDNS Domain, Wireguard Port opened on my FRITZ!Box and routed to internal raspberry pi IP.

**Comment by pheiduck** [comment]
My Setup: Raspberry Pi 4B with Manjaro 6.1 LTS Kernel `nightly` build is working fine.
Do you have any logs @redstripes89 ?

**Comment by pheiduck** [comment]
@redstripes89 please test `ghcr.io/wg-easy/wg-easy:development`
I reverted a change on the `Dockerfile` how it is build on production

**Comment by redstripes89** [comment]
I'm afraid it's not working. 

Wireguard docker log does not show anything special
```
22.12.2023 16:56:29 2023-12-22T15:56:29.840Z Server Listening on http://0.0.0.0:51821
22.12.2023 16:56:29 2023-12-22T15:56:29.845Z WireGuard Loading configuration...
22.12.2023 16:56:29 2023-12-22T15:56:29.851Z WireGuard Configuration loaded.
22.12.2023 16:56:29 2023-12-22T15:56:29.852Z WireGuard Config saving...
22.12.2023 16:56:29 2023-12-22T15:56:29.859Z WireGuard Config saved.
22.12.2023 16:56:29 $ wg-quick down wg0
22.12.2023 16:56:29 $ wg-quick up wg0
22.12.2023 16:56:30 2023-12-22T15:56:30.290Z WireGuard Config syncing...
22.12.2023 16:56:30 $ wg syncconf wg0 <(wg-quick strip wg0)
22.12.2023 16:56:30 2023-12-22T15:56:30.392Z WireGuard Config synced.
22.12.2023 16:56:53 2023-12-22T15:56:53.289Z Server New Session: a0SV1PRmdrx8PNjKR4X9fm82eHeOkL3a
```
Is there any way to enable debug logging or something? 

The Wireguard app on my iPhone does not have any logging, but the app on my Windows 11 laptop says 
`Handshake for peer 1 (<ip>:<port>) did not complete after 5 seconds`

**Comment by pheiduck** [comment]
okay please test again: `ghcr.io/wg-easy/wg-easy:development`
```
docker-compose down
docker system prune -a --volumes
docker-compose up -d
```

**Comment by redstripes89** [comment]
Tried again but still failing

**Comment by pheiduck** [comment]
okay, then its not the colprit how it is build.
can you exec into the docker container. after I revert `--production` flag

**Comment by pheiduck** [comment]
@redstripes89 I am also an iPhone user, I do not have connection issues. 🤔 I will take a deeper look into it after Christmas. Have prepared a separate branch for my „dev doings“ 😉

**Comment by redstripes89** [comment]
Since my laptop cannot connect either, I would suppose that's it's not an iPhone issue. 
Thanks for your work. I'm happy if I can help with further testing after christmas 😊 🎄

**Comment by peterlewis** [comment]
@BerserkeR-Git and @redstripes89 - don't get your hopes up, it prob won't fix, but I've made a partial code reversion to v10 and pushed to `ghcr.io/wg-easy/wg-easy:development`.

Can you please give it a whirl and report back? Thanks!

**Comment by peterlewis** [comment]
Okay. Thanks for letting me know. We'll keep in touch.

**Comment by pheiduck** [comment]
Okay, I published another dev build with disabled nodemon install ghcr.io/wg-easy/wg-easy:development.
Please test again and give feedback. 🌲

**Comment by redstripes89** [comment]
Unfortunately I have to say that it still doesn't work. Same handshake errors.

**Comment by peterlewis** [comment]
As raised by @Comet1903 there appears to be only a partial implementation of the `$WG_PORT` variable leaving `51820` hardcoded in `/src/config.js`.

I note from your kindly-provided `docker-compose.yml` that you appear to both be using custom ports. Hopeful this may resolve. Please report back with your findings after running latest build pushed to `development`.

**Comment by pheiduck** [comment]
@BerserkeR-Git Can you tell us if the network analysis in the web browser queries the "client" file? what is the status of this?

**Comment by LoV432** [comment]
Yes it queries constantly. This is the output while i am attempting to connect using the Phone client. This is on the latest dev branch


```json
[
  {
    "id": "e902a525-c9ce-455c-821a-25e5216ad4da",
    "name": "Phone",
    "enabled": true,
    "address": "10.8.0.2",
    "publicKey": "YarH1pNODWuzGqj2kv7f2hHbiQeX7yRHelrQiYTWJi0=",
    "createdAt": "2023-09-20T07:00:33.165Z",
    "updatedAt": "2023-12-21T20:57:43.457Z",
    "persistentKeepalive": "off",
    "latestHandshakeAt": null,
    "transferRx": 0,
    "transferTx": 0
  },
  {
    "id": "9db86c3a-efb3-4f1c-b0f5-a2452dcaec14",
    "name": "Personal Laptop",
    "enabled": true,
    "address": "10.8.0.3",
    "publicKey": "YolqNOXQi+ggRCRsfmSXMzhygrbokhdRQM12obvO0lU=",
    "createdAt": "2023-09-24T06:07:22.832Z",
    "updatedAt": "2023-12-21T20:57:44.867Z",
    "persistentKeepalive": "off",
    "latestHandshakeAt": null,
    "transferRx": 0,
    "transferTx": 0
  }
]
```

**Comment by pheiduck** [comment]
@LoV432 Sorry, I wanted to know the http status code. Is this 200 or 403?
If so I think this triggering the issue: https://github.com/wg-easy/wg-easy/commit/2a775d4bf7a68c4a0a9371d4c398dc459d03c135

**Comment by LoV432** [comment]
> @LoV432 Sorry, I wanted to know the http status code. Is this 200 or 403? If so I think this triggering the issue: [2a775d4](https://github.com/wg-easy/wg-easy/commit/2a775d4bf7a68c4a0a9371d4c398dc459d03c135)

Ah sorry :D The status code is 200

![image](https://github.com/wg-easy/wg-easy/assets/60856741/d96e5db8-4dd7-493a-a0ed-f7c12d4c67fa)

**Comment by pheiduck** [comment]
Maybe `WG_DEVICE` need to be specified if it is not `eth0`

**Comment by pheiduck** [comment]
A new dev build has been deployed with changes from #700 `ghcr.io/wg-easy/wg-easy:development`

**Comment by redstripes89** [comment]
New build is not working if you don't define WG_INTERFACE variable!
```
26.12.2023 15:04:03 module.exports.WG_INTERFACE = process.env.WG_INTERFACE.toLowerCase() || 'wg0';
26.12.2023 15:04:03                                                        ^
26.12.2023 15:04:03 
26.12.2023 15:04:03 TypeError: Cannot read properties of undefined (reading 'toLowerCase')
26.12.2023 15:04:03     at Object.<anonymous> (/app/config.js:11:56)
26.12.2023 15:04:03     at Module._compile (node:internal/modules/cjs/loader:1356:14)
26.12.2023 15:04:03     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
26.12.2023 15:04:03     at Module.load (node:internal/modules/cjs/loader:1197:32)
26.12.2023 15:04:03     at Module._load (node:internal/modules/cjs/loader:1013:12)
26.12.2023 15:04:03     at Module.require (node:internal/modules/cjs/loader:1225:19)
26.12.2023 15:04:03     at require (node:internal/modules/helpers:177:18)
26.12.2023 15:04:03     at Object.<anonymous> (/app/lib/WireGuard.js:27:5)
26.12.2023 15:04:03     at Module._compile (node:internal/modules/cjs/loader:1356:14)
26.12.2023 15:04:03     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
```

**Comment by redstripes89** [comment]
Besides that, even after definig WG_INTERFACE I'm afraid it's still not working for me 😕

**Comment by pheiduck** [comment]
@redstripes89 and @BerserkeR-Git please test dev build again.

**Comment by pheiduck** [comment]
> Not working :(

Which Kernel is your System using?

**Comment by pheiduck** [comment]
Ah, since `WG_PORT` is not been hardcoded it needs to be defined to the different port as environment variable.

**Comment by pheiduck** [comment]
```diff
version: "3.2"

-networks:
-  vpn:
-    driver: bridge

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:development
    container_name: wg-easy
-   networks:
-      - vpn
    ports:
      - "redacted:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - /volume1/docker/appdata/wg-easy:/etc/wireguard
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - WG_HOST=redacted
      - PASSWORD=redacted
      - WG_INTERFACE=wg0 # Tried different numbers than just wg0
      - WG_DEVICE=eth0 # Tried both eth0 and eth4
      - WG_PORT=redacted
    restart: unless-stopped
```

**Comment by pheiduck** [comment]
@BerserkeR-Git try without the network config

**Comment by pheiduck** [comment]
@BerserkeR-Git I don't know what is causing your error. I have tested your docker-compose file on a Raspberry Pi 4 and it works without any problems

**Comment by pheiduck** [comment]
> Of course I'm using a Synology, that's how this whole thread started it was in the title and being said in many messages. It's the same reason #682 started. We're using @rusty1281 's WG packages (SPK) to get WG support, which has been working flawlessly for a long time. Maybe rusty can provide additional info on them.
> 
> > 4.4.302+ and I'm using this SPK to get WG support; https://www.blackvoid.club/wireguard-spk-for-your-synology-nas/ v1000 SPK for DS1821+ DSM 7.2 [Direct Link](https://www.blackvoid.club/content/files/2023/03/WireGuard-v1000-1.0.20220627.spk)
> 
> There is his website which I linked in my previous message, maybe you can check the v1000 SPK files for yourself for compatibility. This problem has been resolved for most users in #682 but it was still not working for some, and I was told to create this issue (692).

I am working on a solution to get it working without Kernel support for older Kernels here: https://github.com/wg-easy/wg-easy/pull/702 its still WIP.
If you want feel free to halp out :)

**Comment by rusty1281** [comment]
@pheiduck Since 5 days ago and the current latest version of WG it’s running with no issue on any Syno box I have tested. All of those do have WG support via a dedicated SPK that brings support to the box. 

Are you sayin that the new version of WG you are working on will not need additional support from the kernel side?

Just asking to make sure I understand it correctly. 

Tnx!

**Comment by pheiduck** [comment]
As I discovered this: https://github.com/cloudflare/boringtun
I would try to implement it

**Comment by rusty1281** [comment]
> > Since 5 days ago and the current latest version of WG it’s running with no issue on any Syno box I have tested. All of those do have WG support via a dedicated SPK that brings support to the box.
> 
> Have you had someone test with a DS1821+ or a similar model using the v1000 SPK, because nightly is still not working for me. Only latest.
> 
> And it's also not working for @redstripes89 and @LoV432 but their setup is different from mine as well.

Well not sure what the issue is here if the latest is working for you? Current latest is the v8 updated since 5days ago. Are you talking about the latest v7 version? That’s the one working for you?

**Comment by rusty1281** [comment]
> As I discovered this: https://github.com/cloudflare/boringtun I would try to implement it

That’s great news! If this would eliminate the need to custom roll WG support, great. Still for this particular open issue I’m not sure that the SPK that works for year for thousands of users is somehow the issue since the new update of wgeasy. Sure it was a hick up of some sort that you guys fixes for old kernel but this case that Beserker has could be something specific for his system imho. 

Offered to remote to his system to have a look, let’s see if that pans out.

**Comment by rusty1281** [comment]
> `ghcr.io/wg-easy/wg-easy:latest` is working. nightly or development with dark mode UI isn't.

latest also has dark mode ui and no Node warning no more. 

What date is the latest image you are using?

**Comment by pheiduck** [comment]
Yep v9 do not have darkmode it will land into v10

**Comment by pheiduck** [comment]
some other docker service is using it.

**Comment by rusty1281** [comment]
Yes it has no dark mode, that's why I corrected my post, all tests on the latest were done during the day. hehe.

> I just did a `docker system prune -a --volumes` it still says `661ff4d9561e Already exists`. So like I said latest is working but for what ever reason development or nightly is not.

Ok so I dont understand. If the latest is working for you, what's the issue here then? The fix from a week ago is obviously in place.

**Comment by rusty1281** [comment]
> > Yes it has no dark mode, that's why I corrected my post, all tests on the latest were done during the day. hehe.
> > > I just did a `docker system prune -a --volumes` it still says `661ff4d9561e Already exists`. So like I said latest is working but for what ever reason development or nightly is not.
> > 
> > 
> > Ok so I dont understand. If the latest is working for you, what's the issue here then? The fix from a week ago is obviously in place. Why are dev and nightly so important now?
> 
> I misunderstood then, I thought we were supposed to test and get the dark mode version working, which I now learn 'will land into v10'. But yes, with latest the node.js prompt is gone and it is in fact working. But this shows I would still have issues with nightly, future updates AFAIK.

I have just pulled the current `nightly`, running fine:

```
2023-12-26T23:15:24.096Z Server Listening on http://0.0.0.0:51821
2023-12-26T23:15:24.098Z WireGuard Loading configuration...
2023-12-26T23:15:24.101Z WireGuard Configuration loaded.
2023-12-26T23:15:24.101Z WireGuard Config saving...
2023-12-26T23:15:24.103Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
2023-12-26T23:15:24.238Z WireGuard Config syncing...
$ wg syncconf wg0 <(wg-quick strip wg0)
2023-12-26T23:15:24.257Z WireGuard Config synced.
2023-12-26T23:15:44.926Z Server New Session: n3lk97ijBRQ7C6QJRX5xxxxxxxx
```

```
{
  "release": "10",
  "name": "wg-easy",
  "version": "1.0.1",
  "description": "The easiest way to run WireGuard VPN + Web-based Admin UI.",
  "main": "server.js",
  "scripts": {
    "serve": "DEBUG=Server,WireGuard nodemon server.js",
    "serve-with-password": "PASSWORD=wg npm run serve",
    "lint": "eslint .",
    "buildcss": "npx tailwindcss -i ./www/src/css/app.css -o ./www/css/app.css --watch"
  },
  "author": "Emile Nijssen",
  "license": "GPL",
  "dependencies": {
    "bcryptjs": "^2.4.3",
    "debug": "^4.3.4",
    "express": "^4.18.2",
    "express-session": "^1.17.3",
    "qrcode": "^1.5.3",
    "uuid": "^9.0.1"
  },
  "devDependencies": {
    "eslint": "^8.56.0",
    "eslint-config-athom": "^3.1.3",
    "tailwindcss": "^3.4.0"
  },
  "nodemonConfig": {
    "ignore": [
      "www/*"
    ]
  },
  "engines": {
    "node": "18"
  }
}
```
<img width="806" alt="Screenshot 2023-12-27 at 00 18 05" src="https://github.com/wg-easy/wg-easy/assets/5110408/42d878b6-1f4a-4c17-afd7-572a2cc86fb5">

**Comment by redstripes89** [comment]
> > Yes it has no dark mode, that's why I corrected my post, all tests on the latest were done during the day. hehe.
> > > I just did a `docker system prune -a --volumes` it still says `661ff4d9561e Already exists`. So like I said latest is working but for what ever reason development or nightly is not.
> > 
> > 
> > Ok so I dont understand. If the latest is working for you, what's the issue here then? The fix from a week ago is obviously in place. Why are dev and nightly so important now?
> 
> I misunderstood then, I thought we were supposed to test and get the dark mode version working as well, which I now learn 'will land into v10'. But yes, with latest the node.js prompt is gone and it is in fact working. But this shows I would still have issues with nightly, future updates AFAIK. -- And I'm not the only one.

I don’t think you misunderstood! :) 
@pheiduck and @peterlewis are helping us to get our setups running with their latest changes. I think I remember they said not to bring v10 until this issue is fixed. That’s very kind and they are very helpful. And of course we are testing their development stages. 

It’s nice to see that not everyone has this problems but I think @rusty1281 is the one who is misunderstanding this issue. 
Our connections just don’t get set up, and there is no data transport, handshakes are failing.

**Comment by rusty1281** [comment]
> So what changed from latest to nightly that breaks the connection for multiple users here? You're also using a different Synology than me.

Well, you did asked an hour ago to provide additional info, so I am.

> It’s nice to see that not everyone has this problems but I think @rusty1281 is the one who is misunderstanding this issue.
> Our connections just don’t get set up, and there is no data transport, handshakes are failing.

I get that you are having these issues, just wanted to confirm that it is not a general negative experience for everyone using this current nightly version, especially for Syno users, as this open issue started by one Syno user in particular.

Forgot to mention in the previous answer that the transport and handshakes are working fine, not just the fact that the UI boots up.

<img width="830" alt="Screenshot 2023-12-27 at 00 31 47" src="https://github.com/wg-easy/wg-easy/assets/5110408/c187bb2f-9d3d-4b2e-b83c-da6f82893ee3">

**Comment by rusty1281** [comment]
> I don't think it can be the v1000 SPK causing this, right? @rusty1281

I don't see how or why the SPK would be an issue. It worked with v7, it's working with v9 (that also got fixed by the team behind wgeasy). I'm just trying to point out that this is not a general issue when Syno devices are in question. 

I have lost track of who is using what tbh (apart from 1821+ that you use), but again, I just don't see the SPK to be the culprit here for you. To make things more clear I also use v1000 SPK on one of my boxes, and it does run just fine.

**Comment by pheiduck** [comment]
@BerserkeR-Git please show us the output of `ip a`

**Comment by peterlewis** [comment]
@BerserkeR-Git [A few tweaks](https://github.com/wg-easy/wg-easy/pull/691#issuecomment-1872065043) made to the bcrypt implementation, courtesy of @James-Stokes. Unlikely to resolve your issue but, as with any tweak currently, please test `nightly` and report back.

Thanks!

**Comment by redstripes89** [comment]
> @BerserkeR-Git [A few tweaks](https://github.com/wg-easy/wg-easy/pull/691#issuecomment-1872065043) made to the bcrypt implementation, courtesy of @James-Stokes. Unlikely to resolve your issue but, as with any tweak currently, please test `nightly` and report back.
> 
> Thanks!

At least for me it's not working :/

**Comment by pheiduck** [comment]
> At least for me it's not working :/

@redstripes89 Please specify what is not working.

**Comment by pheiduck** [comment]
For Wireguard Logging: https://www.procustodibus.com/blog/2021/03/wireguard-logs/
Maybe then we will get more information about what causes problems.

**Comment by redstripes89** [comment]
> > At least for me it's not working :/
> 
> @redstripes89 Please specify what is not working.

Sorry. Same as before: connection not established and handshake error messages

**Comment by redstripes89** [comment]
> For Wireguard Logging: https://www.procustodibus.com/blog/2021/03/wireguard-logs/ Maybe then we will get more information about what causes problems.

can I setup this logging outside the wireguard docker image or will you provide a version where logging is included? 
As fas as I see, dyndbg is not available for me on RPi4 using DietPi image, and tcpdump / iptables logging has to capture the traffic inside the docker container?

**Comment by pheiduck** [comment]
> can I setup this logging outside the wireguard docker image

You can setup this logging inside the wireguard docker image.

**Comment by redstripes89** [comment]
got it working! 🥳 

I've mapped the container to a different port from the outer world in my docker compose file (note: 12345 is not the actual port): 
```
    ports:
      - "**12345**:51820/udp"
```
and had also set the environment variable `WG_PORT=12345`.
This works for v9.

Since WG_PORT is the port, wireguard will listen to, I thought that when it still listens to 51820 inside the container, I should set WG_PORT=51820. After doing so, the `nightly` image works. 

So I guess there has been at least one change in how this port variable is handled?

**Comment by pheiduck** [comment]
or you have opened port 51820 instead of 12345 on your router.

**Comment by redstripes89** [comment]
> or you have opened port 51820 instead of 12345 on your router.

No, port forwarding only 12345.

**Comment by peterlewis** [comment]
Oh this is making sense. I think some consideration may be needed on this. It makes sense that when setting WG_PORT that the value used to set the `.conf` is variable-ised, but given that it maps internally to `51280` in the `yml` do we need to look to revert those values back to hardcoded? Besides presentation to clients, is there value in the destination port within the container being set to alternatives?

**Comment by peterlewis** [comment]
As it stands, all those who have set a custom port will have their config broken with nightly, as their compose files will still be pointing to `51820` within the container.

**Comment by peterlewis** [comment]
Note that this can be summed-up with the following change to the README, re `$WG_PORT`:

Production:
`The public UDP port of your VPN server. WireGuard will always listen on 51820 inside the Docker container.`

Nightly:
`The public UDP port of your VPN server. This will also change the port wireguard will listen to.`

If we push this change from `nightly` to `production` then all existing setups where a custom `$WG_PORT` variable is being utilised will break.

If it is desired for it to be possible to change the port within the container itself, then this will need to be implemented with a separate variable.

**Comment by centralhardware** [comment]
I have two wg-easy container running on different ports with network host and what I can do from this moment to continue using this project?

**Comment by peterlewis** [comment]
Right. I've pushed a new build to `development` that reflects the above PR (#712). @redstripes89 and @BerserkeR-Git can you please hop on over and test that the behaviour is the same as `production` for you? Thanks!

**Comment by peterlewis** [comment]
> I have two wg-easy container running on different ports with network host and what I can do from this moment to continue using this project?

If the above PR gets merged then you wouldn't need to do anything. This PR does not revert the ability to set the `$WG_PORT` variable, but it aligns the behaviour to that of the `production` branch whereby the port *inside* the container remains as `51820` so as to avoid a breaking change to production.

If it is needed to change the port *inside* the container then consideration will be needed as to the most appropriate way to implement this.

**Comment by centralhardware** [comment]
It's problem, because two processes can't listen one port, in this case 51820

**Comment by peterlewis** [comment]
> It's problem, because two processes can't listen one port, in this case 51820

Why would they be both listening to the same port, if they are running in separate containers? Surely it would be, for example:

Instance 1: `12345:51820`
Instance 2: `23456:51820`

Please to feel free to correct me if I am misunderstanding you.

**Comment by redstripes89** [comment]
`development`working for me aswell with custom port 😄

**Comment by centralhardware** [comment]
Because container running with network mode host and custom wire guard interface name

**Comment by peterlewis** [comment]
Excellent! Am merging this into `nightly` now as, if the behaviour seen in nightly was transposed to `production` then this issue could break things for a significant number of people!

As mentioned above, if it is desired/required to change the port *inside* the container then we will need to consider an appropriate way to implement this.

**Comment by centralhardware** [comment]
So  WG_INTERFACE is useless right now

**Comment by peterlewis** [comment]
Right folks. That fix has been pushed to `nightly`. Feel free to head on over if you are chomping at the bit for your dark mode! :)

**Comment by peterlewis** [comment]
> So WG_INTERFACE is useless right now

Ah yes, I understand what you mean. When operating in `host` networking mode, port cannot be claimed twice, as mentioned in @Comet1903's [PR](https://github.com/wg-easy/wg-easy/pull/700).

So yes, right now `$WG_INTERFACE` is going to be somewhat of a moot variable. Either we need to remove the ability to manually set the interface OR we need to use a separate variable for setting the port INSIDE the container.

In the state that it was in `nightly`, when pushed to `production`, anyone who was making use of a custom `$WG_PORT` variable would see their setups cease working and this would be of considerable disruption as a widespread breaking change.

Can we please continue this discussion in a new Issue that outlines your requirements, so we can progress appropriately?

Thanks!

Peter
